runtime: python311

instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Handlers define how URL paths correspond to application resources.
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: main.py
  
